name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account: zenex-web-next@appspot.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Decode and save JSON
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > $HOME/service-account-key.json

      # After the setup-gcloud step:
      - name: Authenticate with gcloud
        run: |
          gcloud auth activate-service-account zenex-web-next@appspot.gserviceaccount.com --key-file=$HOME/service-account-key.json --project=${{ secrets.GCP_PROJECT }}

      - name: Configure gcloud Project
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}

      - name: Install serve globally
        run: npm install -g serve

      - name: Deploy to App Engine
        run: |
          gcloud app deploy
